### ISSUE TITLE
can't print custom itemgroups?

### ISSUE THREAD

**Issue by marios-andr** [MelanX/RecipePrinter#2]
As the title suggests, when I type the command for printing itemgroups it only allows me to print minecraft itemgroups, not custom

**Comment by MelanX** [comment]
Your custom itemgroup is saved under "minecraft:custom_name"
Try this, please

**Comment by marios-andr** [comment]
I found it, but it crashes my game when I the command runs. The recipeprinter/item_groups directory gets created but there's nothing actually inside. I tried this with vanilla ones, still crashes.

**Comment by MelanX** [comment]
Could you provide the latest.log, please?

**Comment by marios-andr** [comment]
https://pastebin.com/5ixwnenE

**Comment by MelanX** [comment]
I see 🤔 you shouldn’t use it on 1.16.3 🤔
Please try the version 1.0+3 on my jenkins: https://jenkins.melanx.de/job/Recipe%20Printer/job/1.16.x/ this should be compatible with 1.16.3, will update CurseForge file soon.
