### ISSUE TITLE
fromJEI crashes when printing recipe added by Lychee

### ISSUE THREAD

**Issue by lilypuree** [MelanX/RecipePrinter#7]
[crash report](https://github.com/MelanX/RecipePrinter/files/8104464/crash-2022-02-21_02.04.21-server.txt)
[crash log](https://github.com/MelanX/RecipePrinter/files/8104468/2022-02-21-2.log)

Tested with softdrink's hot bubbling water recipe, which uses lychee's item inside recipe type. 
links to the mods:
[Lychee](https://www.curseforge.com/minecraft/mc-mods/lychee)
[Soft Drinks](https://www.curseforge.com/minecraft/mc-mods/soft-drinks)

**Comment by MelanX** [comment]
closed by 7d59ea82db16fe8dfa92b214fa213733cacfd2fd
